source 'https://github.com/CocoaPods/Specs.git'
  target 'GeoAdd' do
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  pod "youtube-ios-player-helper"
  pod 'FBSDKCoreKit'
  pod 'FBSDKShareKit'
  pod 'FBSDKLoginKit'
 end

 